### ISSUE TITLE
Errors in README

### ISSUE THREAD

**Issue by wbenoit26** [alecgunny/deepclean-demo#1]
I ran into a couple issues executing the instructions in the README:

1. When building the containers from the top-level directory as directed, the first argument of the `%file` section in each `apptainer.def` refers to a directory two above the repo itself. Either the build commands should be run in their respective directories, or an absolute path should be used in the definition files.

2. In the command to run training, the `data-fname` arg should be `$DATA_DIR/deepclean-1250916945.0-1250951947.0.hdf5` to match the data file generated during the data generation step

**Comment by alecgunny** [comment]
(2) is a good catch. In reality we should be intify-ing the start/end at save time, and the second term should actually be the duration, not the end timestamp. Implementing both of these rn.

As for (1), this is an interesting question. You definitely don't want absolute paths in the definition files, because they should be fully independent of the build environment. The question is really whether

1. the `README` instructions should be updated to build inside the project directories
2. the `%files` section should use `.` instead of `../..`
3. (2), but the def files all just live at the root level or in a `build` directory and have names like `train.def`, `data.def`, etc.

Curious to get your thoughts on which makes more sense given your experience of just having built this. (1) has the benefit that it treats each project as its own fully-contained build environment (even if it has dependencies in other projects), but requires that you `cd` to each project separately then build it. (2) is easy for a new user who just wants to get up and running in the most automated way possible, but then is confusing if/when you try to build the containers in their corresponding project directory while you're developing them. (3) solves this last issue, but then the relationship between the definition files and the project they're meant to build is less clear.

It's also worth considering the next step of this workflow, where for 99% of experiments you'll be using a pre-built container at `/cvmfs/singularity.opensciencegrid.org` and just binding your local code into this container, so you'll very rarely need to actually build anything unless you're developing the environment. In that case, is it worth adopting (1) as the most straightforward for those who are actually interested in developing the containers?

@ethanmarx interested in your input here as well.

**Comment by EthanMarx** [comment]
My vote is for (1), basically for all the reasons Alec described. To me, `../..` or any relative path is intuitively w.r.t the current directory the file lives in. I think clarity about details of the container build trumps "ease" of building the container.

If the concern is ease of building the containers, we can add a simple bash script or Makefile that will `cd` into the project directories and build the images.

**Comment by wbenoit26** [comment]
I fully agree with (1) as well, I don't think it's too confusing for new users to have to switch directories

**Comment by alecgunny** [comment]
Ok cool thanks gang, I'll push all these changes to a PR now then
